FORMAT: 1A
## GET /
+ Response 200

## GET /not_existed_path
+ Response 404

# GET /api/hello/hikalium
+ Response 200 (application/json; charset=utf-8)

        {"message": "kokodayo hikalium!"}

# POST /api/items

+ Request (application/json)

        {
          "image_url": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+C9QDwADpgGQ/B4OjgAAAABJRU5ErkJggg=="
        }

+ Response 200 (application/json; charset=utf-8)

        {"status": "ok"}

