# https://circleci.com/docs/2.0/postgres-config/#example-ruby-project-with-mysql-and-dockerize
version: 2
jobs:
  build:
    docker:
        - image: 'circleci/golang:latest'
          environment:
            MYSQL_HOSTNAME: 127.0.0.1
            MYSQL_PORT: 3306
            MYSQL_DATABASE: kokodayo_test
            MYSQL_USER: kokodayo
            MYSQL_PASSWORD: kokodayo
        - image: circleci/mysql:8.0.4
          command: [--default-authentication-plugin=mysql_native_password]
          environment:
            MYSQL_ROOT_PASSWORD: kokodayo
            MYSQL_DATABASE: kokodayo_test
            MYSQL_USER: kokodayo
            MYSQL_PASSWORD: kokodayo
    steps:
        - checkout
        - run: sudo apt install -y nodejs npm default-mysql-client
        - run: sudo npm install -g dredd
        - run:
            # Our primary container isn't MYSQL so run a sleep command until it's ready.
            name: Waiting for MySQL to be ready
            command: |
                for i in `seq 1 10`;
                do
                nc -z 127.0.0.1 3306 && echo Success && exit 0
                echo -n .
                sleep 1
                done
                echo Failed waiting for MySQL && exit 1
        - run: make test
